### ISSUE TITLE
KeyError trying to close a BufferWrapper opened by FileSystem.open method

### ISSUE THREAD

**Issue by fpelussobmat** [bmat/bazaar#1]
Hey! Just find out trying to call **BufferWrapper.close** method on an instance returned by **FileSystem.open** method raises a **KeyError** stating the key **name** couldn't be find.

The traceback is the following:
```py
File "/usr/local/lib/python3.6/site-packages/bazaar/bazaar.py", line 34, in hooked r = self.db.update_one({"name": self.file_data["name"], "namespace": self.file_data["namespace"]}, {"$set": {"size": file_size}})
KeyError: 'name'
```

I believe it's related to **bazaar/bazaar.py**'s line 80 where it gets the file data from the database but just reads the **_id** field so it won't include neither **name** or **namespace**.

```py
d = self.db.find_one({"name": path, "namespace": namespace}, {"_id": 1})
```

**Comment by maxpowel** [comment]
Thank you so much @fpelussobmat!
