### ISSUE TITLE
FileSystem.remove() doesn't remove file from filesystem

### ISSUE THREAD

**Issue by bruno-robert** [bmat/bazaar#5]
## Actual Outcome

Calling `FileSystem.remove()` only removes the file from the metadata database (mongoDB) and doesn't remove the underlying file from the file system.

## Expected outcome

Calling `FileSystem.remove()` removes the file from the metadata database (mongoDB) and from the file system (be it local filesystem, S3 etc.)

## Proposed solution

Modify the remove method so that it deletes the underlying file from the file system.

## Alternative solution (to preserve backwards comparability)

Implement new method that deletes the file metadata and the underlying file.

**Comment by franagustin** [comment]
Hi @bruno-robert!
Just saw your issue while implementing a non-related new feature and created a PR to fix it.

Please, let me know any suggestions you have or if it does not solve your needs: https://github.com/bmat/bazaar/pull/6

**Comment by franagustin** [comment]
Closing as we already merged the functionality.
Ping JFYI @bruno-robert
